capture: webcam_capture.cpp
	g++ webcam_capture.cpp -o webcam_capture -std=c++14 `pkg-config --cflags --libs opencv4`

video: webcam_video.cpp
	g++ webcam_video.cpp -o webcam_video -std=c++14 `pkg-config --cflags --libs opencv4`
